<?php
// src/Blogger/BlogBundle/Entity/Repository/XmlRepository.php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Xml4;
/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XmlRepository extends EntityRepository
{
    public function getAllEntries()
    {
        $qb = $this->createQueryBuilder('')
            ->from(Xml4::class,'xml')
            ->select('*');

        return $qb->getQuery()
            ->getResult();
    }
}